services:
  moneyprinterturbo:
    build:
      context: ${DOCKERDIR}/appdata/moneyprinterturbo/src
    container_name: moneyprinterturbo
    security_opt:
      - no-new-privileges:true
    restart: unless-stopped
    profiles: ["apps", "all"]
    networks:
      - default
    ports:
      - "8501:8501"
    environment:
      - TZ=${TZ}
      - PYTHONUNBUFFERED=1
      - PUID=$PUID
      - PGID=$PGID
    volumes:
      - $DOCKERDIR/appdata/moneyprinterturbo/src:/MoneyPrinterTurbo
      - $DOCKERDIR/appdata/moneyprinterturbo/config/config.toml:/MoneyPrinterTurbo/config.toml
      - $DOCKERDIR/appdata/moneyprinterturbo/storage:/MoneyPrinterTurbo/storage
    #  - $DOCKERDIR/appdata/moneyprinterturbo/config/config.toml:/MoneyPrinterTurbo/config.toml
    #  - $DOCKERDIR/appdata/moneyprinterturbo/storage:/MoneyPrinterTurbo/storage
    healthcheck:
      test: ["CMD", "python3", "-c", "import urllib.request; urllib.request.urlopen('http://localhost:8501/_stcore/health')"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    command: ["streamlit", "run", "./webui/Main.py", "--server.address=0.0.0.0", "--server.port=8501", "--server.enableCORS=True", "--browser.gatherUsageStats=False"]
    extra_hosts:
      - "host.docker.internal:host-gateway"
    deploy:
          resources:
            reservations:
              devices:
                - driver: nvidia
                  count: 1
                  capabilities: [gpu]